### ISSUE TITLE
Finne ut hvordan vi skal eksponere credentials til apper

### ISSUE THREAD

**Issue by mortenlj** [navikt/nada-kafkarator#14]
Tanken er at en app skal definere hvilke topics den skal konsumere fra og produsere til, og så skal vi sørge for at den får de nødvendige credentials for å gjøre disse operasjonene. 

Vi må finne ut hvordan vi skal eksponere disse til appene. Det finnes antageligvis flere varianter, så jeg skal prøve å liste opp noen av de jeg kommer på:

- Secrets
- Magisk endepunkt. Krever antageligvis at vi lager noe bibliotekstøtte.
- Proxy. Usikker på hvordan dette kunne vært implementert egentlig, så kanskje ikke.

**Comment by mortenlj** [comment]
Med team namespaces så virker det naturlig å bare opprette en secret `aiven-credentials` i namespacet som gir tilgang til teamets service bruker på Aiven.

For on-site så må vi evt. putte disse i Vault hvis ikke vi bare kan gå for secrets i namespace der og.

**Comment by Kyrremann** [comment]
@mortenlj hadde jo vært kjekt å bruke dette som en liten godteri for å få folk til å bruke team namespaces. Pluss en mindre ting for dere å lage.

**Comment by mortenlj** [comment]
> Pluss en mindre ting for dere å lage.

"Mindre ting å lage" er vi positive til 😀 

Jeg tror egentlig vi kommer til å si vi baserer oss på team namespaces, det er en god del ting som blir enklere da. Dvs. vi støtter ikke at man kjører i "shared namespace".
